# Generated by Django 3.2.25 on 2025-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0194_auto_20250714_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="scratch_image",
            field=models.ImageField(
                blank=True,
                help_text="Image to display in the Scratch tab",
                null=True,
                upload_to="tutorial_images/",
                verbose_name="scratch image",
            ),
        ),
    ]
