# Generated by Django 3.2.25 on 2025-08-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0195_tutorial_scratch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tutorial',
            field=models.ForeignKey(blank=True, help_text='Associated tutorial to display with this contest.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.tutorial', verbose_name='contest tutorial'),
        ),
    ]
