# Generated by Django 3.2.25 on 2025-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0196_add_contest_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL to YouTube video (will be auto-converted to embed format)', null=True, verbose_name='YouTube video URL'),
        ),
    ]
