# Generated by Django 3.2.25 on 2025-10-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0197_tutorial_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Unique browser/device fingerprint for security', max_length=255, null=True, verbose_name='device fingerprint'),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Persistent device identifier cookie', max_length=64, null=True, verbose_name='device ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_registered_at',
            field=models.DateTimeField(blank=True, help_text='When the current device was first registered', null=True, verbose_name='device registration time'),
        ),
    ]
